version: '1'
services:
  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    networks:
      - frontend
    env_file:
      .env.production.local

networks:
  frontend:
    driver: bridge