export enum Service {
  QUESTION_SERVICE = 'QUESTION_SERVICE',
  USER_SERVICE = 'USER_SERVICE',
  COLLABORATION_SERVICE = 'COLLABORATION_SERVICE',
  CHATBOT_SERVICE = 'CHATBOT_SERVICE',
  MATCHING_SERVICE = 'MATCHING_SERVICE',
  WEBSOCKET_GATEWAY = 'WEBSOCKET_SERVICE',
}
