base-externals:
  # Specify DNS names to database servers here
  # We are currently only using one db server in the deployment
  # Alternatively, directly use the cluster private IP directly in the .env file in prod
  mongodbHost: host.docker.internal
  postgresHost: host.docker.internal
  redisHost: host.docker.internal

base-nginx-ingress:
  # Register a domain for the backend to generate TLS/SSL certs
  hostName: localhost
  acmeEmail:
