version: "3"
services:
  gateway:
    build: 
      context: .
      dockerfile: ./apps/gateway/Dockerfile
    depends_on:
      sql-migrations:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
    ports:
      - ${API_GATEWAY_PORT}:${API_GATEWAY_PORT}
    networks:
      - backend
    env_file:
      .env.docker

  question:
    build: 
      context: .
      dockerfile: ./apps/question/Dockerfile
    depends_on:
      sql-migrations:
        condition: service_completed_successfully
    networks:
      - backend
    env_file:
      .env.docker

  user:
    build: 
      context: .
      dockerfile: ./apps/user/Dockerfile
    depends_on:
      sql-migrations:
        condition: service_completed_successfully
    networks:
      - backend
    env_file:
      .env.docker

  collaboration:
    build: 
      context: .
      dockerfile: ./apps/collaboration/Dockerfile
    depends_on:
      sql-migrations:
        condition: service_completed_successfully
    networks:
      - backend
    env_file:
      .env.docker

  matching:
    build: 
      context: .
      dockerfile: ./apps/matching/Dockerfile
    depends_on:
      sql-migrations:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
    networks:
      - backend
    env_file:
      .env.docker

  chatbot:
    build: 
      context: .
      dockerfile: ./apps/chatbot/Dockerfile
    depends_on:
      sql-migrations:
        condition: service_completed_successfully
    networks:
      - backend
    env_file:
      .env.docker

  postgres:
    image: postgres:14.1-alpine
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data # Persist data between restarts
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    networks:
      - backend
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 5s
      timeout: 20s
      retries: 5
      start_period: 20s

  sql-migrations:
    build: 
      context: .
      dockerfile: ./scripts/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      mongo:
        condition: service_healthy
    env_file:
      .env.docker
    environment:
      - QUESTION_SERVICE_MONGODB_URL=mongodb://root:root@mongo:27017/peer-prep-question?authMechanism=DEFAULT
      - COLLABORATION_SERVICE_MONGODB_URL=mongodb://root:root@mongo:27017/peer-prep-collaboration?authMechanism=DEFAULT
    networks:
      - backend

  # rabbitmq:
  #   image: rabbitmq:management
  #   environment:
  #     - RABBITMQ_DEFAULT_USER=guest
  #     - RABBITMQ_DEFAULT_PASS=guest
  #   networks:
  #     - backend
  #   healthcheck:
  #     test: [ "CMD", "rabbitmqctl", "status"]
  #     interval: 5s
  #     timeout: 20s
  #     retries: 5

  redis:
    image: redis:7.2-alpine
    restart: always
    networks:
      - backend
    env_file:
      .env.docker
    command: redis-server --save 60 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  backend:
    driver: bridge
