version: '3'
services:
  http-gateway:
    build:
      context: .
      dockerfile: ./apps/http-gateway/Dockerfile
      target: test
    depends_on:
      sql-migrations:
        condition: service_completed_successfully
    networks:
      - backend
    env_file:
      .env.test

  ws-gateway:
    build:
      context: .
      dockerfile: ./apps/ws-gateway/Dockerfile
      target: test
    depends_on:
      sql-migrations:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
    networks:
      - backend
    env_file: .env.test

  question:
    build:
      context: .
      dockerfile: ./apps/question/Dockerfile
    depends_on:
      sql-migrations:
        condition: service_completed_successfully
    networks:
      - backend
    env_file: .env.test

  user:
    build:
      context: .
      dockerfile: ./apps/user/Dockerfile
    depends_on:
      sql-migrations:
        condition: service_completed_successfully
    networks:
      - backend
    env_file: .env.test

  collaboration:
    build:
      context: .
      dockerfile: ./apps/collaboration/Dockerfile
    depends_on:
      sql-migrations:
        condition: service_completed_successfully
    networks:
      - backend
    env_file: .env.test

  matching:
    build:
      context: .
      dockerfile: ./apps/matching/Dockerfile
    depends_on:
      sql-migrations:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
    networks:
      - backend
    env_file: .env.test

  chatbot:
    build:
      context: .
      dockerfile: ./apps/chatbot/Dockerfile
    depends_on:
      sql-migrations:
        condition: service_completed_successfully
    networks:
      - backend
    env_file: .env.test

  postgres:
    image: postgres:14.1-alpine
    restart: always
    networks:
      - backend
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
      interval: 10s
      timeout: 5s
      retries: 5

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    networks:
      - backend
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 5s
      timeout: 20s
      retries: 5
      start_period: 20s

  sql-migrations:
    build:
      context: .
      dockerfile: ./scripts/Dockerfile
    networks:
      - backend
    depends_on:
      postgres:
        condition: service_healthy
      mongo:
        condition: service_healthy
    env_file: .env.test
    environment:
      - QUESTION_SERVICE_MONGODB_URL=mongodb://root:root@mongo:27017/peer-prep-question?authMechanism=DEFAULT
      - COLLABORATION_SERVICE_MONGODB_URL=mongodb://root:root@mongo:27017/peer-prep-collaboration?authMechanism=DEFAULT

  redis:
    image: redis:7.2-alpine
    restart: always
    networks:
      - backend
    env_file: .env.test
    command: redis-server --save 60 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    healthcheck:
      test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  backend:
    driver: bridge
