{{- $acmeEmail := .Values.acmeEmail | required ".Values.acmeEmail is required." -}}

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: peerprep-clusterissuer
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ $acmeEmail }}
    privateKeySecretRef:
      name: acme-secret
    solvers:
    - http01:
        ingress:
          class: nginx
