apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: peerprep-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ .Values.acmeEmail }}
    privateKeySecretRef:
      name: lets-encrypt-prod
    solvers:
    - http01:
        ingress:
          ingressClassName: nginx
