{{- $mongodbHost := .Values.mongodbHost | required ".Values.mongodbHost is required." -}}
{{- $postgresHost := .Values.postgresHost | required ".Values.postgresHost is required." -}}

---
apiVersion: v1
kind: Service
metadata:
  name: peer-prep-external-postgres-service
spec:
  type: ExternalName
  externalName: {{ $postgresHost }}
  selector: {}

---
apiVersion: v1
kind: Service
metadata:
  name: peer-prep-external-mongodb-service
spec:
  type: ExternalName
  externalName: {{ $mongodbHost }}
  selector: {}
