apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: patch.yaml
    target:
      kind: Deployment
  - path: delete-acme-patch.yaml
  - path: delete-ingress-tls-patch.yaml
    target:
      kind: Ingress

secretGenerator:
  - name: env-file
    envs:
      - .env
