{{- $microserviceName := .Values.microserviceName | required ".Values.microserviceName is required." -}}
{{- $replicaCount := .Values.replicaCount | required ".Values.replicaCount is required." -}}
{{- $imageRepository := .Values.image.repository | required ".Values.image.repository is required." -}}
{{- $imageTag := .Values.image.tag | required ".Values.image.tag is required." -}}
{{- $containerPort := .Values.containerPort | required ".Values.containerPort is required." -}}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $microserviceName }}
spec:
  replicas: {{ $replicaCount }}
  selector:
    matchLabels:
      app: {{ $microserviceName }}
  template:
    metadata:
      labels:
        app: {{ $microserviceName }}
    spec:
      containers:
        - name: {{ $microserviceName }}
          image: {{ $imageRepository }}:{{ $imageTag }}
          imagePullPolicy: Never
          ports:
            - containerPort: {{ $containerPort }}
          envFrom:
            - secretRef:
                name: env-file
