name: build-backend

on:
  push:
    branches:
      - master

jobs:
  build-push-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build
        run: cd backend && cp .env.docker.example .env.docker && docker compose --env-file .env.docker build
      - name: Push
        run: cd backend && docker compose --env-file .env.docker push
