name: frontend-ci

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    name: Frontend Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        commands: ['format:ci', 'lint:ci', build, test]

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: '18'
      - name: Install frontend dependencies
        run: cd frontend; yarn install --frozen-lockfile;
      - name: Run frontend tests
        run: cd frontend; yarn run ${{ matrix.commands }}